name: zhiqiu-env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - tqdm
  - scikit-learn
  - xarray
  - netcdf4
  - pytorch
  - cpuonly  # remove if you want CUDA and replace with pytorch-cuda=12.1 -c nvidia
  - pip
  - pip:
      # add pip-only packages here if needed